### PR TITLE
Adding mafiya69 and a link to MD-Cheetsheat

### PR DESCRIPTION
**Pull request by 0x6773**

### CODE REVIEW

**Comment by 0x6773** [comment]
@leosartaj I think I should add a link to Cheatsheet in [README.md](https://github.com/leosartaj/learn-git/blob/master/README.md) but at which Line?

**Comment by leosartaj** [comment]
Personally I think it's not the best idea to add Cheatsheet as a file. It's will be better if a link is added instead. I guess link can be added after L-16 in README.md.

Thanks for the PR @mafiya69

**Comment by 0x6773** [comment]
@leosartaj

**Comment by leosartaj** [comment]
Looks good. Thanks!

**Pull request merged**
