### PR TITLE
Updated authors.

### PR DESCRIPTION
**Pull request by kausin97**
Made the necessary changes, as it wasn't in alphabetical order before.

### CODE REVIEW

**Comment by ghost** [comment]
Some best practices:
1. Keep minimal no. of commits, but separate them so that each one has a separate "one unit of change". Something like "add X to Y", or "update/fix X".
2. Don't close and open pull-requests unnecessarily. It's considered bad practice, and having a single thread of communication and responses helps the maintainers a lot.

So, you should alteast make this PR into two commits. You can try learning about how to edit, squash and merge commits to make this into two commits by following the links in the README.

**Comment by kausin97** [comment]
I'm reading up on how to squash commits.

**Comment by leosartaj** [comment]
This is just for practice. Squashing won't be necessary, but it always good to know. Thanks for the contribution! Merging.

**Comment by leosartaj** [comment]
Thanks @sumitsahrawat for reviewing this.

**Comment by ghost** [comment]
My pleasure :+1:

**Pull request merged**
